### ISSUE TITLE
Wrong Quote Symbols in German Language

### ISSUE THREAD

**Issue by trueberryless** [trueberryless-org/mutanuq#41]
There is a common mistake in the docs, where the wrong quotes are used:

In German the first inverted comma (in front of the word) needs to be a bottom quote (like a subscript) whereas in English it's like a superscript.

- `"` before a word needs to be replaced by `„`
- `"` after the word needs to be replaced by `“`

There is probably some way to use RegEx...

**Comment by Lotzi** [comment]
Don't do it. You will regret it. Using the englisch version of the " could be excused to be an anglizismus. So it wouldn't even be a mistake

**Comment by trueberryless** [comment]
I did it anyways. Unfortunately, there was no good RegEx or I was to lazy to find it... xD
